/**
 * Bambu filament profile IDs (tray_info_idx) for generic / third-party lines.
 * Sourced from Bambu RFID research (see spool-management bambu.ts).
 */
export const MATERIAL_PROFILE_NAMES: Record<string, string> = {
  GFA00: 'Bambu PLA Basic',
  GFA01: 'Bambu PLA Matte',
  GFA02: 'Bambu PLA Metal',
  GFA03: 'Bambu PLA Impact',
  GFA05: 'Bambu PLA Silk+',
  GFA06: 'Bambu PLA Silk+',
  GFA07: 'Bambu PLA Marble',
  GFA08: 'Bambu PLA Sparkle',
  GFA09: 'Bambu PLA Tough',
  GFA10: 'Bambu PLA Tough+',
  GFA11: 'Bambu PLA Aero',
  GFA12: 'Bambu PLA Glow',
  GFA13: 'Bambu PLA Dynamic',
  GFA15: 'Bambu PLA Galaxy',
  GFA16: 'Bambu PLA Wood',
  GFA17: 'Bambu PLA Translucent',
  GFA18: 'Bambu PLA Lite',
  GFA50: 'Bambu PLA-CF',
  GFG00: 'Bambu PETG Basic',
  GFG01: 'Bambu PETG Translucent',
  GFG02: 'Bambu PETG HF',
  GFG50: 'Bambu PETG-CF',
  GFB00: 'Bambu ABS',
  GFB01: 'Bambu ASA',
  GFB02: 'Bambu ASA Aero',
  GFB50: 'Bambu ABS-GF',
  GFB51: 'Bambu ASA-CF',
  GFC00: 'Bambu PC',
  GFC01: 'Bambu PC FR',
  GFN03: 'Bambu PA-CF',
  GFN04: 'Bambu PAHT-CF',
  GFN05: 'Bambu PA6-CF',
  GFN06: 'Bambu PPA-CF',
  GFN08: 'Bambu PA6-GF',
  GFU00: 'Bambu TPU 95A HF',
  GFU01: 'Bambu TPU 95A',
  GFU02: 'Bambu TPU for AMS',
  GFS00: 'Bambu Support W',
  GFS01: 'Bambu Support G',
  GFS02: 'Bambu Support for PLA',
  GFS03: 'Bambu Support for PA/PET',
  GFS04: 'Bambu PVA',
  GFS05: 'Bambu Support for PLA/PETG',
  GFS06: 'Bambu Support for ABS',
  GFL00: 'PolyLite PLA',
  GFL01: 'PolyTerra PLA',
  GFL03: 'eSUN PLA+',
  GFL04: 'Overture PLA',
  GFL05: 'Overture Matte PLA',
  GFL95: 'Generic PLA High Speed',
  GFL96: 'Generic PLA Silk',
  GFL98: 'Generic PLA-CF',
  GFL99: 'Generic PLA',
  GFG96: 'Generic PETG HF',
  GFG97: 'Generic PCTG',
  GFG98: 'Generic PETG-CF',
  GFG99: 'Generic PETG',
  GFB98: 'Generic ASA',
  GFB99: 'Generic ABS',
  GFC99: 'Generic PC',
  GFN96: 'Generic PPA-GF',
  GFN97: 'Generic PPA-CF',
  GFN98: 'Generic PA-CF',
  GFN99: 'Generic PA',
  GFP95: 'Generic PP-GF',
  GFP96: 'Generic PP-CF',
  GFP97: 'Generic PP',
  GFP98: 'Generic PE-CF',
  GFP99: 'Generic PE',
  GFR98: 'Generic PHA',
  GFR99: 'Generic EVA',
  GFS97: 'Generic BVOH',
  GFS98: 'Generic HIPS',
  GFS99: 'Generic PVA',
  GFT01: 'Bambu PET-CF',
  GFT02: 'Bambu PPS-CF',
  GFT97: 'Generic PPS',
  GFT98: 'Generic PPS-CF',
  GFU98: 'Generic TPU for AMS',
  GFU99: 'Generic TPU',
};
